[package]
name = "freely_tauri"
version = "0.7.0"
authors = ["Gottesman <gottesman@example.com>"]
edition = "2021"

[dependencies]
tauri = { version = "2.8.4", features = ["protocol-asset"] }
tokio = { version = "1.47.1", features = ["rt-multi-thread", "macros", "time"] }
reqwest = { version = "0.11.27", features = ["json", "gzip", "brotli", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
base64 = "0.22"
urlencoding = "2.1"
dirs = "4.0"

[build-dependencies]
tauri-build = { version = "2.4.0", features = [] }
